[book]
title = "DendryNexus Documentation, Reference and Book"
authors = ["fleetoise and contributors (see AUTHORS)"]
language = "en"
src = "content"


[output.html]
default-theme = "rust"

[output.html.fold]
enable = true
level = 0
